### ISSUE TITLE
having problems installing with python3.10

### ISSUE THREAD

**Issue by ghanim-mukhtar** [mjcarroll/r2s#10]
I just saw this in the roscon2024, amazing and thx for this effort. I wanted to test quickly but I had an issue with python version and just wanted to see if there is a quick workaround. 

I am working with a dockerized ROS2 humble container. 

```
The currently activated Python version 3.10.12 is not supported by the project (^3.11).
Trying to find and use a compatible version. 

Poetry was unable to find a compatible version. If you have one, you can explicitly use it via the "env use" command.
```

**Comment by ghanim-mukhtar** [comment]
So to go through the installation I simply installed the python3.11 then when I ran it I have other issue:
```
user@user$ poetry run r2s
No module named 'rclpy._rclpy_pybind11'
The C extension '/opt/ros/humble/lib/python3.10/site-packages/_rclpy_pybind11.cpython-311-x86_64-linux-gnu.so' isn't present on the system. Please refer to 'https://docs.ros.org/en/humble/Guides/Installation-Troubleshooting.html#import-failing-without-library-present-on-the-system' for possible solutions
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ros/r2s/r2s/main.py", line 1, in <module>
    from r2s.ui import UI 
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ros/r2s/r2s/ui.py", line 17, in <module>
    class UI(App):
  File "/home/ros/r2s/r2s/ui.py", line 44, in UI
    def on_node_selected(self, message: NodeSelected) -> None:
                                        ^^^^^^^^^^^^
NameError: name 'NodeSelected' is not defined

```

**Comment by mjcarroll** [comment]
It looks like we are conflicting with the system python version here.  I may be able to reduce the dependency to Python 3.10.  Textual itself only requires 3.8, so that may be worth a shot: https://github.com/Textualize/textual/blob/ca923f7bd4eb665909526db7ff8d539d0c90b66a/pyproject.toml#L43

**Comment by mjcarroll** [comment]
Actually, there is a longer answer here, which is to package r2s for selected ros distributions, but as we are in early phases of building here, I don't think that it's worth it at this point.

**Comment by ghanim-mukhtar** [comment]
Okay, thanks a lot  for the answer, and yes I understand the cost/benefit analysis you gave. 

Just please don't close the issue just yet, I will try to see how to reduce this python dependency to 3.10 and give it another test before closing it myself.

**Comment by mbuijs** [comment]
FYI: on my Ubuntu 22.04 / ROS2 Humble install (no container) changing the python dependency to 3.10 and updating the `poetry.lock` file worked fine.
