### ISSUE TITLE
Fix installation with Humble

### ISSUE THREAD

**Issue by mjcarroll** [mjcarroll/r2s#18]
Currently the poetry file specifies a newer version of python than what comes with Humble.  This can likely be relaxed based on https://github.com/mjcarroll/r2s/issues/10#issuecomment-2444033510

**Comment by robintomar1** [comment]
Hi @mjcarroll, I recently installed this project on my ubuntu 22 with ros2 humble. I have logged all the steps I went through to get it running. This might help you to fix it for humble.

`poetry install` : bash: poetry: command not found

`sudo apt-get install poetry` : Installation done with warning. WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

`poetry install` The currently activated Python version 3.10.12 is not supported by the project (^3.11). Trying to find and use a compatible version.

Poetry was unable to find a compatible version. If you have one, you can explicitly use it via the "env use" command

**_Then I modified the pyproject.toml file and modified python version to 3.10_**

`poetry lock --no-update`

<details>
<summary>Output</summary>

 Resolving dependencies... (24.0s)Writing lock filepoetry installInstalling dependencies from lock filePackage operations: 67 installs, 1 update, 0 removals

- Installing exceptiongroup (1.2.2)
- Installing iniconfig (2.0.0)
- Installing packaging (24.1)
- Installing pluggy (1.5.0)
- Installing tomli (2.2.1)
- Installing coverage (7.6.1)
- Installing mdurl (0.1.2)
- Installing pytest (8.3.3)
- Installing typing-extensions (4.12.2)
- Installing distlib (0.3.8)
- Installing frozenlist (1.4.1)
- Installing idna (3.10)
- Installing markdown-it-py (3.0.0)
- Installing multidict (6.1.0)
- Installing pytest-cov (5.0.0)
- Downgrading setuptools (75.6.0 -\> 75.1.0)
- Installing uc-micro-py (1.0.3)
- Installing aiohappyeyeballs (2.4.0)
- Installing aiosignal (1.3.1)
- Installing async-timeout (4.0.3)
- Installing attrs (24.2.0)
- Installing linkify-it-py (2.0.3)
- Installing markupsafe (2.1.5)
- Installing mdit-py-plugins (0.4.2)
- Installing pygments (2.18.0)
- Installing six (1.16.0)
- Installing yarl (1.12.1)
- Installing aiohttp (3.10.6)
- Installing docutils (0.21.2)
- Installing jinja2 (3.1.4)
- Installing pyparsing (3.1.4)
- Installing python-dateutil (2.9.0.post0)
- Installing rich (13.8.1)
- Installing aiohttp-jinja2 (1.6)
- Installing catkin-pkg (1.0.0)
- Installing distro (1.9.0)
- Installing filelock (3.16.1)
- Installing platformdirs (4.3.6)
- Installing pyyaml (6.0.2)
- Installing textual (0.74.0)
- Installing cfgv (3.4.0)
- Installing click (8.1.7)
- Installing execnet (2.1.1)
- Installing identify (2.6.1)
- Installing msgpack (1.1.0)
- Installing nodeenv (1.9.1)
- Installing mypy-extensions (1.0.0)
- Installing pathspec (0.12.1)
- Installing rospkg (1.5.1)
- Installing syrupy (4.7.1)
- Installing textual-serve (1.1.1)
- Installing tree-sitter (0.23.0)
- Installing virtualenv (20.26.5)
- Installing black (24.4.2)
- Installing isort (5.13.2)
- Installing lark-parser (0.12.0)
- Installing mypy (1.11.2)
- Installing numpy (2.1.2)
- Installing pre-commit (2.21.0)
- Installing psutil (6.0.0)
- Installing pytest-asyncio (0.24.0)
- Installing pytest-textual-snapshot (1.0.0)
- Installing pytest-xdist (3.6.1)
- Installing rosdistro (0.9.1)
- Installing textual-dev (1.6.1)
- Installing types-setuptools (67.8.0.0)
- Installing types-tree-sitter (0.20.1.20240311)
- Installing types-tree-sitter-languages (1.10.0.20240612)

</details>

Installing the current project: r2s (0.1.0)

`poetry run r2s`

<details>
<summary>Output</summary>

No module named 'netifaces' Traceback (most recent call last): File "", line 1, in File "/usr/lib/python3.10/importlib/**init**.py", line 126, in import_module return \_bootstrap.\_gcd_import(name\[level:\], package, level) File "", line 1050, in \_gcd_import File "", line 1027, in \_find_and_load File "", line 1006, in \_find_and_load_unlocked File "", line 688, in \_load_unlocked File "", line 883, in exec_module File "", line 241, in \_call_with_frames_removed File "/home/dusty/ros2_ws/src/r2s/r2s/r2s/main.py", line 1, in from r2s.ui import UI File "/home/dusty/ros2_ws/src/r2s/r2s/r2s/ui.py", line 17, in class UI(App): File "/home/dusty/ros2_ws/src/r2s/r2s/r2s/ui.py", line 44, in UI def on_node_selected(self, message: NodeSelected) -\> None: NameError: name 'NodeSelected' is not defined

</details>

`pip install netifaces`

<details>
<summary>Output</summary>

Requirement already satisfied: netifaces in /usr/lib/python3/dist-packages (0.11.0) WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

</details>

**_The I modified pyproject.toml again and added `netifaces = "^0.11.0" `below rosdistro line_**

`poetry lock --no-update` 

<details>
<summary>Output</summary>

Resolving dependencies... (0.8s)

Writing lock file

poetry install Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

- Installing netifaces (0.11.0)

Installing the current project: r2s (0.1.0)

</details>

`poetry run r2s`

!!!!!!!!!!!!!! worked !!!!!!!!!!!!!
![image](https://github.com/user-attachments/assets/848d77ba-a973-433d-8973-18f1c6b87638)

**Comment by fake-name** [comment]
This actually works all the way back to iron/20.04, if you remove a couple of the 3.10 type annotations (I think in 4 places) and allow older numpy. It's totally fine on python 3.8.

I'm stuck (by hardware) in iron.
